name: 'hello workd js action'
description: 'greet someone and record the time'
author: nicledomaS
branding:
  color: black
  icon: terminal
  
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: 'World'
outputs:
   time:
   description: 'The time we greeted you'
   
runs:
  using: 'node16'
  main: 'index.js'
