name: test my custom action
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: output the string
        uses: lnxiang/test-custom-action@main
        with:
          who-to-greet: 'The big big World'
